src/main/java/domain/Users.java
package domain;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

@Entity
@NamedQuery(name="users.all", query="SELECT u FROM Users u")
public class Users extends EntityBase {

    @OneToMany
    public Set<Events> eventsList;

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    protected int id;

    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    @Temporal( TemporalType.DATE )
    Date date = new Date();

    private String login;

    private String password;

    @Column(columnDefinition = "varchar(50) default 'default.jpg'")
    private String photo;
    @Temporal( TemporalType.DATE )
    private Date birthday;
    private String register = dateFormat.format(date);
    private String email;

    @ManyToOne
    private Groups groupID;


    public String getPhoto() {
        if(photo==null) {
            photo = "default.jpg";
        }

        return photo;
    }

    public void setPhoto(String photo) {
        if(photo==null) {
            photo = "default.jpg";
        }

        this.photo = photo;
    }

    public String getRegister() {
        return register;
    }

    public void setRegister(String register) {
        this.register = register;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Groups getGroupID() {
        return groupID;
    }

    public void setGroupID(Groups groupID) {
        this.groupID = groupID;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set<Events> getEvents() {
        return eventsList;
    }

    public void setEvents(Set<Events> eventsList) {
        this.eventsList = eventsList;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }
}

web/add_event.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="template.xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="content">
        <div class="i_message">
            <h1>Dodaj ogłoszenie</h1>
            Przed dodaniem ogłoszenia pamiętaj, żeby zapoznać się z regulaminem.
            Ogłoszenie będzie widoczne dla wszystkich użytkowników oraz wyświetlane na stronie głównej serwisu.
            Wypełnij każdą rubrykę formularza,żeby dodanie ogłoszenia zakończyło się prawidłowo.
        </div><br />

        <h:form value="#{eventBean.event}">
            <p:inputText id="title" class="e_input" value="#{eventBean.event.title}">
                <p:watermark for="title" value="Podaj tytuł..." />
            </p:inputText>

            <p:calendar styleClass="e_calendar" id="mask" value="#{eventBean.event.dateday}" pattern="dd-MM-yyyy" mask="true">
                <p:watermark for="mask" value="dzień-miesiąc-rok" />
                <f:convertDateTime pattern="dd-MM-yyyy" />
            </p:calendar>

            <p:calendar styleClass="e_calendar" id="time" value="#{eventBean.event.hour}" pattern="HH:mm a" timeOnly="true">
                <p:watermark for="time" value="godzina-minuta" />
                <f:convertDateTime pattern="HH:mm a" />
            </p:calendar><br />

            <p:inputTextarea class="e_textarea" id="content" value="#{eventBean.event.description}">
                <p:watermark for="content" value="Zamieść resztę informacji na temat wydarzenia..." />
            </p:inputTextarea><br />

            <h1>Ustal dane adresowe:</h1>
            <p:inputText id="city" class="e_input" value="#{eventBean.event.city}">
                <p:watermark for="city" value="Miasto..." />
            </p:inputText><br /><br />

            <p:inputText id="street" class="e_input" value="#{eventBean.event.street}">
                <p:watermark for="street" value="Ulica..." />
            </p:inputText><br /><br />

            <p:inputText id="streetnumber" class="e_input" value="#{eventBean.event.streetnumber}">
                <p:watermark for="streetnumber" value="Numer budynku..." />
            </p:inputText><br /><br />

            <p:commandButton class="e_submit" value="Wyślij" action="#{eventBean.saveEvent}" />
        </h:form>
    </ui:define>
</ui:composition>

web/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="template.xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="content">
        <h:form rendered="#{not empty user}">
        <div class="i_message">
            <h1>Wydarzenia</h1>
            <p:dataTable value="#{eventBean.events}" var="item" style="margin: -20px;">

                <p:column styleClass="e_photo">
                    <f:facet name="header"></f:facet>
                    <img src="http://localhost:8080/EPC_war_exploded/css/img/event.jpg" class="e_event" /><br />
                </p:column>

                <p:column>
                    <f:facet name="header">Informacje</f:facet>
                    <div class="e_title">#{item.title}</div>
                    #{item.description}<br /><br />
                    Dowiedz się więcej: <a href="http://localhost:8080/EPC_war_exploded/profiles/#{item.title}">rozszerz</a>
                </p:column>

                <p:column styleClass="e_add">
                    <f:facet name="header">Dodatkowe</f:facet>
                    <ul>
                        <li><label>Autor:</label> <a href="http://localhost:8080/EPC_war_exploded/profiles/">#{item.author}</a></li>
                        <li><label>Data spotkania:</label>
                            <h:outputText value="#{item.dateday}">
                                <f:convertDateTime pattern="dd/MM/yyyy" />
                            </h:outputText>
                        </li>
                        <li><label>Miasto:</label> #{item.city}</li>
                        <li><label>Ulica:</label> #{item.street}</li>
                        <li><label>Nr budynku:</label> #{item.streetnumber}</li>
                    </ul>
                </p:column>
            </p:dataTable>
        </div>
        </h:form>

        <h:form rendered="#{empty user}">
            <img src="http://localhost:8080/EPC_war_exploded/css/img/stopu.png" class="stop_photo" />
        </h:form>
    </ui:define>
</ui:composition>

web/index.jsp
<% response.sendRedirect("home.jsf"); %>

web/register.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      template="template.xhtml"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="content">
        <div class="i_message">
            <h1>Rejestracja konta</h1>
            Witaj na etapie rejestracji! Żeby założyć konto, wystarczy podać login i hasło. Ważnym jest fakt, aby login, którego masz zamiar użyć, nie był już używany przez inną osobę.
            Zakładając konto, uzyskujesz dostęp do swojego profilu, a także do zamieszczania ogłoszen.
        </div><br />
        <h:form id="userform">
        <div class="register_left">Identyfikator:</div>
        <p:inputText class="input" id="login" value="#{userBean.user.login}">
            <p:watermark for="login" value="Podaj login" />
        </p:inputText><br /><br />

        <div class="register_left">Zabezpieczenie:</div>
        <p:password class="input" match="re-password" id="password" value="#{userBean.user.password}">
            <p:watermark for="password" value="Podaj hasło" />
        </p:password><br /><br />

        <div class="register_left">-</div>
        <p:password class="input" id="re-password" value="#{userBean.user.password}">
            <p:watermark for="re-password" value="Powtórz hasło" />
        </p:password><br /><br />

        <div class="register_left">Poczta</div>
        <p:inputText class="input" id="email" value="#{userBean.user.email}">
            <p:watermark for="email" value="Podaj adres e-mail" />
            <f:validateRegex
                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
        </p:inputText><br /><br />

        <div class="register_left">Data urodzenia:</div>
        <p:calendar styleClass="calendar" id="mask" value="#{userBean.user.birthday}" pattern="dd-MM-yyyy" mask="true">
            <p:watermark for="mask" value="dzień-miesiąc-rok" />
        </p:calendar><br /><br />

        <p:commandButton class="submit" value="Zarejestruj się" action="#{userBean.saveUser}" />
        </h:form>
    </ui:define>

</ui:composition>

web/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
    <title>Mój projekcik!</title>
    <link rel="stylesheet" type="text/css" href="http://localhost:8080/EPC_war_exploded/css/global.css" />
</h:head>
<f:view contentType="text/html">
<h:body>
<div class='header'></div>
    <ui:include src="addons/user_menu.xhtml" />
    <div class='right_block'>
        <ui:insert name="content" />
    </div>
</h:body>
</f:view>
</html>